"""Add bafta_winner_year to Movie model

Revision ID: 4b054b5305cd
Revises: f476b2e6a696
Create Date: 2025-05-26 03:36:53.502027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b054b5305cd'
down_revision = 'f476b2e6a696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bafta_winner_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('bafta_winner_year')

    # ### end Alembic commands ###
