"""Added BAFTA nominees (1949–2025)

Revision ID: cdacb820953d
Revises: 4b054b5305cd
Create Date: 2025-05-26 13:03:34.428916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdacb820953d'
down_revision = '4b054b5305cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
