"""fix oscars db batch mode named constraint

Revision ID: f476b2e6a696
Revises: 8789f927d81e
Create Date: 2025-05-25 19:40:37.299792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f476b2e6a696'
down_revision = '8789f927d81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oscar_awards', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_oscar_awards_movie_id_movies', 'movies', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oscar_awards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_oscar_awards_movie_id_movies', type_='foreignkey')

    # ### end Alembic commands ###
